### ISSUE TITLE
Problem with sequelize-bluebird ?

### ISSUE THREAD

**Issue by ghost** [panjiesw/ah-nodemailer-plugin#2]
Very strange issue here. Here's my config/api.js:

```
plugins: [
        'ah-sequelize-plugin',
        'ah-nodemailer-plugin',
        'ah-newrelic-plugin'
      ],

```

It produces the following error:

```
api_1 | /home/api/node_modules/sequelize/node_modules/sequelize-bluebird/js/main/errors.js:84
api_1 | AggregateError.prototype.length = 0;
api_1 |                                 ^
api_1 | TypeError: Cannot assign to read only property 'length' of Error
api_1 |     at Object.<anonymous> (/home/api/node_modules/sequelize/node_modules/sequelize-bluebird/js/main/errors.js:84:33)
api_1 |     at Module._compile (module.js:456:26)
api_1 |     at Object.Module._extensions..js (module.js:474:10)
api_1 |     at Module.load (module.js:356:32)
api_1 |     at Function.Module._load (module.js:312:12)
api_1 |     at Module.require (module.js:364:17)
api_1 |     at require (module.js:380:17)
api_1 |     at module.exports (/home/api/node_modules/sequelize/node_modules/sequelize-bluebird/js/main/promise.js:34:14)
api_1 |     at Object.<anonymous> (/home/api/node_modules/sequelize/node_modules/sequelize-bluebird/js/main/bluebird.js:24:38)
api_1 |     at Module._compile (module.js:456:26)
```

If I remove `ah-nodemailer-plugin` line, everything works just fine.
Any idea?

**Comment by ghost** [comment]
I fixed this by declaring `ah-nodemailer-plugin` before `ah-sequelize-plugin` in my plugin list.

**Comment by ghost** [comment]
That was related to bluebird - see petkaantonov/bluebird/issues/291
